metaplex-foundation/docs

docusaurus.config.js

Super tiny change. Currently, clicking the edit button takes you to an incorrect link, so this fix just makes the edit button work correctly.

Fixed Docusaurus editUrl

---

docs/create-candy/04-upload-assets.md

If you follow the tutorial you will have candy-machine-cli.ts in `~/metaplex-foundation/metaplex/js/packages/cli/src/` but this part of the tutorial says `~/metaplex/js/packages/cli/src/`. So I think `metaplex-foundation/` is missing

Fixing candy-machine-cli.ts location

---

src/css/custom.css

improve readability of stability link

---

docs/architecture/deep_dive/overview.md

Link was pointing to instruction set for token-vault rather than token-metadata

Correct href for the link to the instruction set

---

docs/nft-standard.md

The Solana address in the example Metadata JSON file does not evaluate to a valid Solana public key: it's too short and uses non-base58 characters. I've replaced it with https://solscan.io/account/xEtQ9Fpv62qdc1GYfpNReMasVTe9YW5bHJwfVKqo72u which is the creator address for the SolFlare Holidays NFT.

replace invalid example Solana address w/ valid one

---

docs/candy-machine-v2/06-verify-upload.md
docs/candy-machine-v2/07-mint-tokens.md

Form `CMv2`, in the Verify and Mint pages, the `-cp` (config path) option is incorrectly documented as part of the commends.
I have removed them as to avoid confusion for others reading the docs.
Close issue #122 after merge.

removed -cp from mint and verify

---

docs/candy-machine-v2/03-configuration.md

Hopefully this helps reduce the number of questions about storage options by encouraging people to use `arweave-sol` on mainnet.

make arweave-sol recommended method for mainnet

---

docs/candy-machine-v2/08-mint-frontend.md

Updating the docs to point individuals at `candy-machine-ui` since `fair-launch` has been removed

Updating CMv2 docs to reflect the removal of fair-launch

---

docs/token-metadata/v1.0.0/_category_.json
docs/token-metadata/v1.1.0/_category_.json
docs/token-metadata/v1.1.0/getting-started.md
docs/token-metadata/v1.1.0/overview.md
docs/token-metadata/v1.1.0/specification.md
docusaurus.config.js

- adds global rust syntax highlighting
- sidebar: move v1.1.0 above v1.0.0 to emphasis the latest version
- uses more markdown headers to allow deep links
- uses deep links and adds links to MPL
- formats technical terms with backticks
- spelling corrections

Improvements to v1.1.0 docs

---

docs/candy-machine-v2/02-configuration.md

Hi, this updates the configuration guide for CMv2 to include the nft.storage options added in https://github.com/metaplex-foundation/metaplex/pull/1512
I'm happy to write a more detailed example if that's of interest :)

add config options for nft.storage uploads

---

docs/candy-machine-v2/02-configuration.md
docs/overviews/storage_overview.md

This updates the Candy Machine v2 configuration doc to indicate that the `nftStorageKey` is now optional, as of https://github.com/metaplex-foundation/metaplex/pull/1757
I also added a section about NFT.Storage to the Storage Overview doc, with a link to [our new Solana / Metaplex page on the NFT.Storage docs site](https://nft.storage/docs/how-to/mint-solana).
Let me know if there's anything else that makes sense to update!
@stegaBOB if you have a minute to review, that would be awesome :)

update docs for using nft.storage

---

docs/token-metadata/specification.md

There are misplaced square brackets around "Token Metadata" in the docs. As far as I can tell, this struct has been renamed to `Metadata` and is referred to as the "token `Metadata` struct" elsewhere on the same page so that is what I updated it to here.

Fix typo in the docs

---

docs/auction-house/cli.md

- Explain using either latest version or a tagged release.
- Explain that currently `execute_sale` requires signing by auction house
authority, the buyer, or the seller.

Updating Auction House CLI instructions

---

docs/candy-machine-v2/10-sign-nfts.md

Currently the documentation is incorrect. signing of a single token does not work through the cache file with -c but -m and the metadata address

metadata account address instead of cache file

---

docs/airdrops/create-gumdrop.md

Gumdrop is hard to grasp for some users. Therefore added one sentence that the airdrop has to be **claimed**.
Also --distribution-list was completely missing although it is always a required parameter.

Clarify Gumdrop docs

---

docs/01-programs/01-token-metadata/03-instructions.md

Image link for `Set token standard` instruction was broken in `programs > token-metadata > instructions`

Broken image link in Token metadata instructions

---

docs/03-developer-tools/00-sugar/06-commands.md

The `launch` command was missing from the commands reference. This PR adds it.

fix: add launch command to commands reference

---

docs/03-developer-tools/00-sugar/03-guides/04-sugar-for-cmv3.md

Looks like a copy paste error. The guard to require token payment is called tokenPayment, not tokenGuard

Sugar guard for token payment is not tokenGate

---

docs/01-programs/02-candy-machine/02-candy-machine-settings.md
docs/01-programs/02-candy-machine/03-managing-candy-machines.md

Fixes a variable name typo in the candy machine settings docs, `sellerFreeBasisPoints` should be `sellerFeeBasisPoints`.
Also, adds missing parentheses in JavaScript sample code.

Fix variable name in candy machine settings & missing parentheses

---

docs/03-developer-tools/00-sugar/03-guides/04-sugar-for-cmv3.md

In the current basic guide we are pointing the user to a sugar tag which is outdated. Deserialization of guards does not work with it!
With this change we point to the general release page and not a specific tag.

Cmv3 release url

---

docs/01-programs/01-token-metadata/05-certified-collections.md

The Token Metadata handlers prove that the collection mint is a valid mint account owned by SPL token, so that part of the check is unnecessary for clients of Token Metadata. For Solana programs this means one less account they have to pass in so is worth clarifying.

clarify verified collection check

---

docs/04-guides/07-archived/01-burn-token.md

The archived burn guide was just referencing a new guide that will be created "soon".
This adds a link to the guide instead

add link to burn guide

---

docs/03-developer-tools/00-sugar/03-guides/02-working-with-sugar.md

The docs were not linking to the correct page.
https://docs.metaplex.com/developer-tools/sugar/overview/quick-start

Add link to quick start section.

---

docs/05-resources/00-rpc-providers.md

GetBlock is a competitive RPS provider that can be compared to big whales in this sphere like QuickNode and Alchemy https://getblock.io/blog/best-blockchain-prc-providers-for-2023-researching-cost-efficiency/ So it definitely should be added

Add Another RPC Provider - GetBlock to the list

---

docs/03-developer-tools/00-sugar/02-tutorials/00-my-first-candy-machine.md
docs/04-guides/00-candy-machine-ui.md

Currently many pages reference CM v2 without mentioning it visible it enough.
This creates confusion for users. The PR adds two warnings for it.
A proper rework of the sugar section is still required

Add info for CM v3

---

docs/01-programs/02-candy-machine/08-minting.md
docs/01-programs/02-candy-machine/09-available-guards/07-gatekeeper.md
docs/01-programs/02-candy-machine/09-available-guards/09-nft-burn.md
docs/01-programs/02-candy-machine/09-available-guards/10-nft-gate.md
docs/01-programs/02-candy-machine/09-available-guards/11-nft-payment.md
docs/01-programs/02-candy-machine/09-available-guards/15-third-party-signer.md

The docs are incorrect currently. On some pages it is shown that the guard settings should be set like this when calling the mint function:
```js
const { nft } = await metaplex.candyMachines().mint({
candyMachine,
collectionUpdateAuthority,
group: "nft",
settings: {
thirdPartySigner: { signer: thirdPartySigner },
nftPayment: { mint: nftFromRequiredCollection.address },
},
});
```
the object is called guards though, not settings. Like this:
```js
const { nft } = await metaplex.candyMachines().mint({
candyMachine,
collectionUpdateAuthority,
group: "nft",
guards: {
thirdPartySigner: { signer: thirdPartySigner },
nftPayment: { mint: nftFromRequiredCollection.address },
},
});
```

fix: use guards object for minting

---

docs/01-programs/03-auction-house/08-how-to-guides/00-manage-auction-house-using-cli.md

Thanks to #404 I realized that the docs currently refer to the deprecated-cli repo even though there is a active cli file for auction house.

use latest CLI

---

docs/05-resources/00-rpc-providers.md

Chainstack has been added as an additional provider and placed in alphabetical order relative to the other providers.

Added Chainstack to provider list

---

docs/01-programs/02-candy-machine/11-how-to-guides/00-my-first-candy-machine-part1.md
docs/01-programs/02-candy-machine/11-how-to-guides/01-my-first-candy-machine-part2-umi.md
docs/01-programs/02-candy-machine/11-how-to-guides/01-my-first-candy-machine-part2.md
docs/03-developer-tools/00-sugar/01-overview/01-installation.md
docs/03-developer-tools/00-sugar/03-guides/04-sugar-for-cmv3.md

following issues have been fixed:
- `create-config` instead of `config create`
- Mention the alpha version for CM v3 even though there is a stable version released for months
- do not warn in the JS SDK mintpage guide that it will not work for pNFT / royalty enforcement / the latest sugar version

Sugar v2.1.1 released

---

docs/01-programs/02-candy-machine/08-minting.md

If pNFT shall be minted but the tokenStandard field is not provided Umi does not throw a proper error message, but instead references the allowList guard.
This PR aims to help users to be aware of that tokenStandard field.

add TokenStandard field

---

docs/01-programs/01-token-metadata/03-instructions.md

`Utilize` can be signed by the owner, not the update authority, as can be seen in the [code](https://github.com/metaplex-foundation/metaplex-program-library/blob/a3251589bf4b79378b2d75d3587702a0385c3529/token-metadata/program/src/processor/uses/utilize.rs#L109C15-L109C46)

fix info about who can invoke the `Utilize` ix
