docs/nft-standard.md

fixed `trait-value` / `value` inconsistency and added HTML support to reflect support in the Metaplex storefront.

Fixed naming inconsistancy and added HTML support

---

docs/about/introduction.md

An attempt to remove some redundancies and excessive words.

Removed some redundancies

---

docs/about/introduction.md
docs/community.md
docs/overviews/_category_.json
docs/overviews/storage_overview.md
package.json
src/arweave-cost-calc.jsx
yarn.lock

- Adds documentation about storage options
- Includes pricing information and an arweave cost calculator

Pricing & storage docs

---

docs/create-candy/05-verify-upload.md

Added command to verify upload

Update docs to verify upload

---

.gitignore
docs/architecture/basic_flow.md
docusaurus.config.js
package.json
yarn.lock

@adamjeffries  Am I on the right track here. In an attempt to understand the whole process in depth I created some diagrams and re-worded some of the docs. 
I would love some feedback if you think this will help the community.
Here is a screenshot of the rendered page for convenience.

(WIP) - Added documentation and changed flow of basic mint and auction

---

.github/workflows/deploy.yml

Switches deploys from a human account to a service account.

use service account for deploys

---

docs/development/clients/js-sdk/examples.md

Adds examples for JS SDK which was used by WP team

docs: add more examples for js sdk

---

docs/create-candy/03-validate-assets.md

i found how to validate nft assets and double-checked. I added it to our docs
source: https://hackmd.io/@levicook/HJcDneEWF#Prerequisites

added validate nft assets

---

docs/create-candy/02-prepare-assets.md

[Typo] Update 02-prepare-assets.md

---

docs/create-candy/11-withdraw.md

removed info about error
merge after fix in metaplex

removed message about error

---

docs/contact.md
docs/security-policy.md

https://app.asana.com/0/1201300038256928/1201484084248944

add contact and security policy pages

---

docs/stability.md
src/css/custom.css

https://app.asana.com/0/1201333981856889/1201417693023097/f

add stability page

---

docs/create-candy/08-mint-tokens.md

Looks like there was a small copy and paste error
+ adding --env devnet for better understanding

fix: mint_multiple tokens command

---

docs/create-candy/02-prepare-assets.md

Fix typo in 02-prepare-assets.md

---

docs/nft-standard.md

The definition of an NFT was lacking in  our docs, this helps wallets and companies integrate with us in a more standard way

Adds what is an NFT

---

docs/architecture/basic_flow.md

Fixed to be `Creating A Token Metadata Account`

Archi > Basic flow - wrong title

---

docs/burn-token.md

added section with info about burn token

---

docs/nft-standard.md

I don't believe a single wallet or exchange supports these features. Not even we support this. We should probably think about removing it potentially.

Remove unused additional attributes

---

docs/candy-machine-v2/03-configuration.md
docs/candy-machine-v2/09-update.md
docs/candy-machine-v2/10-withdraw.md

Also added a note regarding the goLiveDate when using whitelist with presale + captcha settings.

Added notes about updating the number of items of a CMv2

---

docs/candy-machine-v2/09-update.md

Without the file renaming which Github thinks was a conflict.

add show command to update section

---

docs/candy-machine-v2/01-getting-started.md
docs/candy-machine-v2/02-configuration.md
docs/candy-machine-v2/03-preparing-assets.md
docs/candy-machine-v2/06-mint-tokens.md
docs/candy-machine-v2/07-mint-frontend.md
docs/candy-machine-v2/08-update.md

* Clone a tag as single command
* Civic T&C
* Command and output formatting improvements

Few formatting improvements

---

docs/candy-machine-v2/02-configuration.md

Found it missing in the official docs and only figured out the right params via the errors in the console.

Update info on `storage` option of `config.json`.

---

docs/airdrops/create-gumdrop.md

Fix location of Table of Contents as it's currently in the middle of the page instead of being on top.
https://docs.metaplex.com/airdrops/create-gumdrop#drop-types

Fix Table of Contents location

---

docs/candy-machine-v2/09-withdraw.md

Update the docs to include `withdraw` and `withdraw_all` info. In conjunction with this PR: https://github.com/metaplex-foundation/metaplex/pull/1754

Updated withdraw docs

---

docs/auction-house/cli.md
docs/auction-house/definition.md
docs/auction-house/faq.md
docs/candy-machine-v1/01-introduction.md
docs/candy-machine-v1/02-update-cm.md
docs/candy-machine-v1/03-mint-tokens.md
docs/candy-machine-v1/04-create-mint-site.md
docs/candy-machine-v1/05-cm-errors.md
docs/candy-machine-v1/06-withdraw.md
docs/candy-machine-v2/00-introduction.md
docs/candy-machine-v2/01-getting-started.md
docs/candy-machine-v2/02-configuration.md
docs/candy-machine-v2/03-preparing-assets.md
docs/candy-machine-v2/04-creating-candy-machine.md
docs/candy-machine-v2/05-verify-upload.md
docs/candy-machine-v2/07-mint-frontend.md
docs/candy-machine-v2/08-update.md
docs/candy-machine-v2/09-withdraw.md
docs/fair-launch/01-introduction.md
docs/mint-lists.md
docs/token-metadata/specification.md

Added new lines between admonition boundaries and the admonition content to comply with docusaurus suggestions

Fix admonition formatting

---

docs/candy-machine-v2/01-getting-started.md
docs/storefront/installation.md
docs/token-metadata/getting-started.md

Latest tagged version is currently broken. this PR comments out the version suggestions.

Remove latest version

---

docs/auction-house/definition.md
docs/auction-house/faq.md

Adding feature header to the definition and calling out receipts as something that should be indexed in FAQ.

Adding documentation for Auction House receipts.

---

docs/auction-house/definition.md
docs/auction-house/faq.md

I couldn't find a precedent for examples so threw it in a numbered list inside an INFO block. Let me know if there's a better way to format it.

Public vs Private bid documentation

---

docs/candy-machine-v2/02-configuration.md

Added Encore Docs

---

docs/auction-house/faq.md

Small typo and other clarification fixes.

auction house faq fixes

---

docs/candy-machine-v2/03-preparing-assets.md

Added verify_assets to preparing your assets

---

docs/airdrops/create-gumdrop.md

Reverts metaplex-foundation/docs#222
Feature is not live yet.

Revert "Gumdrop/cmv2 frozen whitelist tokens docs"

---

docs/auction-house/cli.md

Saller Fee Typo.
Changer to Seller fee

Update cli.md (Fix Typo)

---

docs/candy-machine-v2/01-getting-started.md

Just the jaz that needs a lil update

Update the jaz

---

docs/airdrops/create-gumdrop.md

relative to here the link should be up one directory

Correct Link to candy-machine-v2 introduction

---

docs/candy-machine-v2/03-preparing-assets.md

changed "otherwhise" to "otherwise"
"theses" to "these"

spelling error

---

docs/candy-machine-v2/01-getting-started.md

Update 01-getting-started.md - typo

---

docs/token-metadata/specification.md

Reverts metaplex-foundation/docs#246

Revert "Add collection diagram"

---

docs/candy-machine-v2/02-configuration.md

Added explanations:
--purpose of Civic Captcha Pass
--best practice guidance

Added context for Civic gatekeeper

---

docs/sugar/06-asset-preparation-and-deployment.md

This PR:
- adds a description for Sugar `bundlr` command
- fixes small typos

Added bundlr command description

---

docs/about/history.md

`initative` to `initiative` at line 13

Fix typo in history.md

---

docs/03-developer-tools/00-sugar/05-configuration.md
docs/03-developer-tools/00-sugar/07-upload-methods.md

Updates the docs for some bug fixes and enhancements that just landed in Sugar `main`.

refactor: update config and upload methods

---

docs/04-guides/04-community.md

add link to community guides

---

docs/04-guides/06-archived/01-burn-token.md

The current guide is not closing all accounts and therefore also do not return all SOL.
Next step is to write a new guide.

Archive spl token burn guide

---

docs/01-programs/01-token-metadata/05-certified-collections.md

Update 05-certified-collections.md - typo

---

docs/03-developer-tools/00-sugar/02-tutorials/00-my-first-candy-machine.md

e.g:
works: https://www.solaneyes.com/address/6886xPKD5V8T927fJnktPCd7JBREsfEBnjCGu1LSm5y5?cluster=devnet
does not work: https://www.solaneyes.com/address/6886xPKD5V8T927fJnktPCd7JBREsfEBnjCGu1LSm5y5devnet
you need to change the network from the UI of solaneyes.

The link works without devnet

---

docs/03-developer-tools/00-sugar/03-guides/04-sugar-for-cmv3.md

changed destiantion to destination

Fix typo in config

---

docs/03-developer-tools/00-sugar/05-reference/02-upload-methods.md

Add an explanation of the custom domain configuration for AWS.

Add aws custom domain

---

docs/03-developer-tools/00-sugar/01-overview/00-introduction.md
docs/07-security.md

Added the sugar audit to a tooltip on the overview page and created a developer tool audit table  and new text to the security page

Added sugar audit

---

docusaurus.config.js
src/components/Feedback/index.js

As discussed with Daeshawn introduce Happyreact and use a token connected with a different Mail.

new Happy React token

---

docs/04-guides/05-community.md

Adding a few videos from my YouTube channel, which has quite decent amount of watch hours and has helped the community a lot. 
The videos include:
* CandyMachine V2
* CandyMachine UI
* Sugar
My YouTube channel: https://www.youtube.com/@Key_Strokes

Add community guides videos by KeyStrokes

---

docs/04-guides/05-community.md

Adding a new video from my YouTube channel on using Candy Machine V3 and Sugar alpha to Create Solana NFT Collection.
My YouTube channel: https://www.youtube.com/@Key_Strokes

Add community guides videos by KeyStrokes for Candy Machine V3 and Sugar alpha

---

docs/05-resources/00-rpc-providers.md

Document RPC Providers in more details

---

docs/01-programs/01-token-metadata/05-certified-collections.md

One suggestion from Twitter was to link to examples of how to do this in JS and Rust. It seems simple enough that this isn't necessary, but we could add it if it would be helpful.

further clarify collection warning 

---

docs/01-programs/02-candy-machine/10-how-to-guides/00-my-first-candy-machine-part1.md

Currently the asset folder does not contain collection.png and collection.json. This results in errors when uploading with the latest sugar version.

add collection to guide

---

docs/04-guides/01-cli-wallet.md

remove ftx from docs

---

docs/01-programs/06-hydra/00-intro.md

Replace not exsiting var with defined on the top.

Update of Hydra Introduction doc

---

docs/01-programs/01-token-metadata/07-using-nfts.md

Changed the fields to match the source code.
'Multiple' variant instead of 'Multiple(u64)' for UseMethod enum 'Total' field in Uses struct instead of 'Available'

update fields to match source code

---

docs/04-guides/05-community.md

Adding two new videos from my YouTube channel on using Candy Machine V3 and Sugar to Create Solana NFT Collection.
My YouTube channel: https://www.youtube.com/@Key_Strokes

Add videos for community guides by KeyStrokes - Candy Machine V3 - Wallet Based Whitelist Minting, and guide for Windows

---

docs/04-guides/05-community.md

Added a community guide for starter mint UI for collection deployed with sugar 2.1.1

Added a community guide for starter mint UI for sugar 2.1.1

---

docs/03-developer-tools/00-sugar/03-guides/04-sugar-for-cmv3.md

This PR adds the configuration for `Allocation`, `ProgramGate` and `Token2022Payment` guards to the Sugar CMv3 guide.

Add guards configuration

---

docs/07-security.md

Preview for page I changed: https://docs-git-danenbm-update-sec-audit-metaplex.vercel.app/security

Update sec audit dates

---

docs/01-programs/02-candy-machine/09-programmable-nfts.md

update link to programmable nfts guide.
[possible ref](https://github.com/metaplex-foundation/mpl-token-metadata/issues/19)

update programmable nfts broken link

---

docs/01-programs/01-token-metadata/00-overview.md
docs/01-programs/01-token-metadata/04-token-standard.md

broken [pNFT guide](https://github.com/metaplex-foundation/mpl-token-metadata/blob/main/programs/token-metadata/program/ProgrammableNFTGuide.md) links

update: broken links to pNFT guides

---

docs/01-programs/04-compression/index.md

- update link to bubblegum program
- add link to developer hub docs

fix: broken link to cNFT program
